[project]
name = "pptmcpseriver"
version = "0.1.0"
description = "讯飞智文PPT生成服务MCP Server"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mcp[cli]>=1.12.1",
    "requests>=2.31.0",
    "requests-toolbelt>=1.0.0",
    "starlette>=0.27.0",
    "uvicorn>=0.23.0",
]
